### ISSUE TITLE
is there a way to detect release mode?

### ISSUE THREAD

**Issue by samjarman** [amazon-archives/BSMobileProvision#4]
Any ideas on trying to detect release mode? As far as I can see, it reports dev even if in release mode (running from xcode). 

Note: I am using this from a compiled framework.

**Comment by mishagray** [comment]
it's not designed to detect whether the code is build with Release or Debug...
It's designed to see how the app is SIGNED.   If you build in Xcode usually it's signed by a developer cert (and will report dev).   If you archive it and sign it for distribution, than running it may show release.   In practice I only ever saw "AppStore" when my app was released on the AppStore.   But you should be able to test with AdHoc (or Enterprise) vs Dev before you release.
